# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Back-end"

on:  # yamllint disable-line rule:truthy
    pull_request: null
    push:
        branches:
        - "master"
# Add [skip ci] to commit message to skip CI.

permissions: {}  # yamllint disable-line rule:braces

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    unit_tests:
        name: "2️⃣ Unit and functional tests"
        strategy:
            matrix:
                php-version:
                - "8.1"
                dependencies:
                - "lowest"
                - "locked"
                - "highest"
        runs-on: "windows-latest"
        timeout-minutes: 5
        steps:
        -
            name: "Checkout repository"
            uses: "actions/checkout@v3.6.0"
        -
            name: "Set up PHP"
            uses: "shivammathur/setup-php@2.25.5"
            with:
                php-version: "${{ matrix.php-version }}"
        -
            name: "Install dependencies"
            uses: "ramsey/composer-install@2.2.0"
            with:
                dependency-versions: "${{ matrix.dependencies }}"
        -
            name: "Execute unit tests"
            run: "./vendor/bin/phpunit --version"
